language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover  

after_script:
  - php vendor/bin/coveralls -v
